version: '3'

services:
  api:
    container_name: template
    image: thutgtz/template:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: npm test