version: '3'

services:
  api:
    container_name: cicd-pipeline
    image: thutgtz/cicd-pipeline:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: npm test