version: '3'

services:
  api:
    container_name: cicd-template
    build:
      context: .
      dockerfile: Dockerfile
    volumes :
      - /app/node_modules
      - .:/app
    ports:
      - "5000:5000"
    command:  npm start
